plugins {
    id 'dev.architectury.loom' version '1.7-SNAPSHOT' apply false
    id 'architectury-plugin' version '3.4-SNAPSHOT'
    id 'com.github.johnrengelman.shadow' version '8.1.1' apply false
}

architectury {
    minecraft = project.minecraft_version
}

allprojects {
    group = rootProject.maven_group
    version = rootProject.mod_version
}

tasks.register("printEnv") {
    doLast {
        def envFile = new File(System.getenv("GITHUB_ENV"))
        envFile.append("MOD_VERSION=$rootProject.mod_version\n")
        envFile.append("RELEASE_NAME=$rootProject.archives_name-$rootProject.mod_version\n")
        envFile.append("GAME_VERSIONS=[1.19, 1.20)\n")
    }
}

subprojects {
    apply plugin: 'dev.architectury.loom'
    apply plugin: 'architectury-plugin'
    apply plugin: 'maven-publish'

    base {
        archivesName = "$rootProject.archives_name-$project.name"
    }

    loom {
        silentMojangMappingsLicense()
    }

    dependencies {
        minecraft "net.minecraft:minecraft:$rootProject.minecraft_version"
        mappings loom.officialMojangMappings()
    }

    java {
        withSourcesJar()

        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    tasks.withType(JavaCompile).configureEach {
        it.options.release = 17
    }

    publishing {
        publications {
            mavenJava(MavenPublication) {
                artifactId = base.archivesName.get()
                from components.java
                pom {
                    name = "anvian's Lib"
                    description = "A small utility library for Anvian's mods."
                    url = 'https://github.com/anviaan/anvians-lib/'
                    licenses {
                        license {
                            name = 'GNU GPLv3'
                            url = 'https://github.com/anviaan/anvians-lib/blob/main/LICENSE'
                            distribution = 'repo'
                        }
                    }
                    developers {
                        developer {
                            name = 'anvian'
                        }
                    }
                }
            }
        }

        repositories {
            maven {
                name = "Repsy"
                url = uri("https://repo.repsy.io/mvn/anvian/anvians-lib")
                credentials {
                    username = "anvian"
                    password = project.findProperty("gpr.token") ?: System.getenv("REPSY_TOKEN")
                }
            }
        }
    }
}
