plugins {
    id 'net.fabricmc.fabric-loom-remap' version "${loom_version}"
    id 'maven-publish'
}

def COMPATIBLE_VERSIONS = '[1.15, 1.16)'

tasks.register("printEnv") {
    doLast {
        def envFile = new File(System.getenv("GITHUB_ENV"))
        envFile.append("MOD_VERSION=${project.mod_version}\n")
        envFile.append("RELEASE_NAME=${project.archives_base_name}-${project.minecraft_version}-${project.mod_version}\n")
        envFile.append("GAME_VERSIONS=${COMPATIBLE_VERSIONS}\n")
    }
}

version = project.mod_version
group = project.maven_group
base {
    archivesName = "${project.archives_base_name}-${project.minecraft_version}"
}

repositories {
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings loom.officialMojangMappings()
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"

    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"
}

processResources {
    def version = project.version
    inputs.property "version", version

    filesMatching("fabric.mod.json") {
        expand "version": version
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 8
}

java {
    withSourcesJar()

    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

jar {
    def projectName = project.name
    inputs.property "projectName", projectName

    from("LICENSE") {
        rename { "${it}_$projectName" }
    }
}

publishing {
    publications {
        create("mavenJava", MavenPublication) {
            from components.java
        }
    }

    repositories {
        maven {
            name = "Reposilite"
            url = uri(
                    version.toString().endsWith("SNAPSHOT")
                            ? "https://maven.anvian.net/snapshots"
                            : "https://maven.anvian.net/releases"
            )
            credentials {
                username = project.findProperty("reposilite.user") ?: System.getenv("REPOSILITE_USER")
                password = project.findProperty("reposilite.token") ?: System.getenv("REPOSILITE_TOKEN")
            }
        }
    }
}
