# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
mod_version = 1.4.1
maven_group = net.anvian.bee_info
archives_name = MoreBeeInfo
enabled_platforms = fabric,forge

# Minecraft properties
minecraft_version = 1.19

# Dependencies
fabric_loader_version = 0.16.10
fabric_api_version = 0.58.0+1.19
forge_version = 1.19-41.1.0

# Anvian's Lib
anvianslib_version = 1.4