# Project
version=1.4
group=net.anvian.bee_info
java_version=21

# Common
minecraft_version=1.21
mod_name=MoreBeeInfo
mod_author=anvian
mod_id=bee_info
license=GPL-3.0
credits=
description=Add the number of bees and honey level in the bee nest and beehive!
minecraft_version_range=[1.21, 1.21.2)
neo_form_version=1.21-20240613.152323
parchment_minecraft=1.21
parchment_version=2024.06.23

# Fabric
fabric_version=0.100.1+1.21
fabric_loader_version=0.15.11

# NeoForge
neoforge_version=21.0.37-beta
neoforge_loader_version_range=[4,)

# Anvian's Lib
anvianslib_version = 1.0

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
